//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateFolder
    {
        public int folder_id { get; set; }
        public string folder_name { get; set; }
        public string description { get; set; }
    }
}
